#!/usr/bin/env bash

#   Copyright The buildx Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

set -eu -o pipefail -x

if [ -x "$(command -v greadlink)" ]; then
	# on macOS, GNU readlink is ava (greadlink) can be installed through brew install coreutils
	cd "$(dirname "$(greadlink -f "$BASH_SOURCE")")/.."
else
	cd "$(dirname "$(readlink -f "$BASH_SOURCE")")/.."
fi

# see also ".mailmap" for how email addresses and names are deduplicated

{
	cat <<-'EOH'
	# This file lists all individuals having contributed content to the repository.
	# For how it is generated, see `scripts/generate-authors.sh`.
	EOH
	echo
	git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > AUTHORS
