#!/usr/bin/env bash

#   Copyright The buildx Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

. $(dirname $0)/util
set -eu -o pipefail -x

: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi

lintDocker() {
  export DOCKER_BUILDKIT=1
  iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
  docker build --iidfile $iidfile -f ./hack/dockerfiles/lint.Dockerfile --force-rm .
  iid=$(cat $iidfile)
  docker rmi $iid
  rm -f $iidfile
}

lint() {
  buildctl build $progressFlag --frontend=dockerfile.v0 \
    --local context=. --local dockerfile=. \
    --frontend-opt filename=./hack/dockerfiles/lint.Dockerfile
}

case $buildmode in
"buildkit")
  lint
  ;;
"docker-buildkit")
  lintDocker
  ;;
*)
	echo "buildctl or docker with buildkit support is required"
  exit 1
  ;;
esac
