#!/usr/bin/env bash

#   Copyright The buildx Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

TAG=$1
OUT=$2

set -eu -o pipefail

: ${PLATFORMS=linux/amd64}
: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi


usage() {
  echo "usage: ./hack/release <tag> <out>"
  exit 1
}

if [ -z "$TAG" ] || [ -z "$OUT" ]; then 
  usage
fi


set -x

buildctl build $progressFlag --frontend=dockerfile.v0 \
  --local context=. --local dockerfile=. \
  --opt target=release \
  --opt platform=$PLATFORMS \
  --exporter local \
  --exporter-opt output=$OUT