#!/usr/bin/env bash

#   Copyright The buildx Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

. $(dirname $0)/util
set -eu -o pipefail -x

: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi

case $buildmode in
"buildkit")
   output=$(mktemp -d -t buildctl-output.XXXXXXXXXX)
  buildctl build $progressFlag --frontend=dockerfile.v0 --local context=. --local dockerfile=. \
    --frontend-opt target=update \
    --frontend-opt filename=./hack/dockerfiles/vendor.Dockerfile \
    --output type=local,dest=$output
  rm -rf ./vendor
  cp -R "$output/out/" .
  rm -rf $output
  ;;
*)
  iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
  case $buildmode in
  "docker-buildkit")
    export DOCKER_BUILDKIT=1
    docker build --iidfile $iidfile -f ./hack/dockerfiles/vendor.Dockerfile --target update --force-rm .
    ;;
  *)
		echo "buildctl or docker with buildkit support is required"
	  exit 1
    ;;
  esac
  iid=$(cat $iidfile)
  cid=$(docker create $iid noop)
  rm -rf ./vendor

  docker cp $cid:/out/go.mod .
  docker cp $cid:/out/go.sum .
  docker cp $cid:/out/vendor .

  docker rm $cid
  rm -f $iidfile
  ;;
esac
