#!/usr/bin/env sh

#   Copyright The buildx Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

: ${PREFER_BUILDCTL=}
: ${PREFER_LEGACY=}
: ${CLI_PLATFORM=}

newerEqualThan() { # $1=minimum wanted version $2=actual-version
  [ "$1" = "$(printf "$1\n$2" | sort -V | head -n 1)" ]
}

buildmode="legacy"
if [ "$PREFER_BUILDCTL" = "1" ]; then
  buildmode="buildkit";
else
  serverVersion=$(docker info --format '{{.ServerVersion}}')
  experimental=$(docker info --format '{{.ExperimentalBuild}}')
  if [ "$PREFER_LEGACY" != "1" ] && ( newerEqualThan "18.09" $serverVersion || \
    ( newerEqualThan "18.06" $serverVersion && [ "true" = "$experimental" ] ) || \
    [ "$DOCKER_BUILDKIT" = "1" ]); then
    buildmode="docker-buildkit";
  fi
fi

if [ -z "$CLI_PLATFORM" ]; then
	rawos=$(uname -s)
	if [ "$rawos" = "Darwin" ]; then
		CLI_PLATFORM="darwin/amd64"
	elif uname -s | grep MINGW 2>&1 >/dev/null ; then
		CLI_PLATFORM="windows/amd64"
	fi
fi

